<?php

$project_root = dirname(__FILE__, 2);
include_once 'test.php';
include_once 'router.php';
include_once 'static.php';
include_once 'page/aboutUsPage.php';
include_once 'page/homePage.php';
include_once 'controller/login_get.php';
include_once 'controller/login_post.php';
include_once 'page/newSpacePage.php';
include_once 'controller/new_space.php';
include_once 'page/dettaglioSpazioPage.php';
include_once 'controller/dettaglioSpazio.php';
include_once 'page/editSpacePage.php';
include_once 'controller/edit_space.php';
include_once 'controller/spazio.php';
include_once 'page/prenotazioneFormPage.php';
include_once 'controller/reservation_new_post.php';
include_once 'controller/reservation_new_get.php';
include_once 'controller/reservation_detail.php';
include_once 'controller/reservation_update_get.php';
include_once 'controller/reservation_update_post.php';
include_once 'controller/reservation_delete.php';
include_once 'page/newUserPage.php';
include_once 'controller/new_user.php';
include_once 'page/editUserPage.php';
include_once 'controller/edit_user.php';
include_once 'controller/logout.php';
include_once 'controller/dashboard.php';
include_once 'page/dashboardDocentePage.php';
include_once 'page/dashboardAmministratorePage.php';
include_once 'page/editPasswordPage.php';
include_once 'controller/edit_password.php';
include_once 'page/dettaglioUtentePage.php';
include_once 'controller/reservations.php';
include_once 'controller/delete_user.php';

$about_us = new AboutUsPage();
$homepage = new HomePage();
$login = new LoginPost();
$spazio_endpoint = new SpazioEndpoint();
$newSpacePage = new NewSpacePage();
$newSpace = new NewSpace();
$editSpacePage = new EditSpacePage();
$editSpace = new EditSpace();
$newUserPage = new newUserPage();
$newUser = new NewUser();
$editUserPage = new EditUserPage();
$editUser = new EditUser();
$logout = new Logout();
$editPasswordPage = new EditPasswordPage();
$editPassword = new EditPassword();
$dettaglioUtentePage = new DettaglioUtentePage();
$deleteUser = new DeleteUser();

$router = new Router();

$router->add(new Test());
$router->add(new StaticPage('about_us', $about_us));
$router->add(new StaticPage('', $homepage));
$router->add($login);
$router->add($spazio_endpoint);
$router->add(new StaticPage('spazi/nuovo', $newSpacePage));
$router->add($newSpace);
$router->add(new DettaglioSpazio());
$router->add(new Dashboard());
$router->add(new StaticPage('spazi/modifica', $editSpacePage));
$router->add($editSpace);
$router->add(new ReservationNewPost());
$router->add(new ReservationNewGet());
$router->add(new ReservationDetail());
$router->add(new ReservationUpdateGet());
$router->add(new ReservationUpdatePost());
$router->add(new ReservationDelete());
$router->add(new StaticPage('utenti/nuovo', $newUserPage));
$router->add($newUser);
$router->add(new StaticPage('utenti/modifica', $editUserPage));
$router->add($editUser);
$router->add($logout);
$router->add(new StaticPage('cruscotto/modifica-password', $editPasswordPage));
$router->add($editPassword);
$router->add(new StaticPage('utenti/utente', $dettaglioUtentePage));
$router->add(new Reservations());
$router->add($deleteUser);
$router->add(new LoginGet());
