<?php

$project_root = dirname(__FILE__, 2);
include_once 'test.php';
include_once 'router.php';
include_once 'static.php';
include_once 'page/aboutUsPage.php';
include_once 'page/homePage.php';
include_once 'controller/login_get.php';
include_once 'controller/login_post.php';
include_once 'page/newSpacePage.php';
include_once 'controller/new_space.php';
include_once 'page/dettaglioSpazioPage.php';
include_once 'controller/dettaglioSpazio.php';
include_once 'page/editSpacePage.php';
include_once 'controller/edit_space.php';
include_once 'controller/spazio.php';
include_once 'page/prenotazioneFormPage.php';
include_once 'controller/reservation_new_post.php';
include_once 'controller/reservation_new_get.php';
include_once 'controller/reservation_detail.php';
include_once 'controller/reservation_update_get.php';
include_once 'controller/reservation_update_post.php';
include_once 'controller/reservation_delete.php';
include_once 'page/newUserPage.php';
include_once 'controller/new_user.php';
include_once 'page/editUserPage.php';
include_once 'controller/edit_user.php';
include_once 'controller/logout.php';
include_once 'controller/dashboard.php';
include_once 'page/dashboardDocentePage.php';
include_once 'page/dashboardAmministratorePage.php';
include_once 'page/editPasswordPage.php';
include_once 'controller/edit_password.php';
include_once 'page/dettaglioUtentePage.php';
include_once 'controller/reservations.php';
include_once 'controller/delete_user.php';
include_once 'controller/utenti.php';

$router = new Router();

// $router->add(new Test());
$router->add(new StaticPage('about_us', new AboutUsPage()));
$router->add(new StaticPage('', new HomePage()));
$router->add(new LoginPost());
$router->add(new SpazioEndpoint());
$router->add(new StaticPage('spazi/nuovo', new NewSpacePage()));
$router->add(new NewSpace());
$router->add(new DettaglioSpazio());
$router->add(new Dashboard());
$router->add(new StaticPage('spazi/modifica', new EditSpacePage()));
$router->add(new EditSpace());
$router->add(new ReservationNewPost());
$router->add(new ReservationNewGet());
$router->add(new ReservationDetail());
$router->add(new ReservationUpdateGet());
$router->add(new ReservationUpdatePost());
$router->add(new ReservationDelete());
$router->add(new StaticPage('utenti/nuovo', new newUserPage()));
$router->add(new NewUser());
$router->add(new StaticPage('utenti/modifica', new EditUserPage()));
$router->add(new EditUser());
$router->add(new Logout());
$router->add(new StaticPage('cruscotto/modifica-password', new EditPasswordPage()));
$router->add(new EditPassword());
$router->add(new StaticPage('utenti/utente', new DettaglioUtentePage()));
$router->add(new Reservations());
$router->add(new DeleteUser());
$router->add(new LoginGet());
$router->add(new UtenteEndpoint());

